version: '3.8'

services:
  credit-scoring-api:
    build: .
    container_name: credit-scoring-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - ./models:/app/models:ro  # Read-only models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://credit-scoring-h7mv.onrender.com/docs#/Health/health_check_api_health_get"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s